### ISSUE TITLE
농부 선택 시, 선택이 되었다는 표시를 해주세요.

### ISSUE THREAD

**Issue by yoondeong** [ksh9409255/diaryServer#3]
현재 농부를 선택했을 때, 선택되었는지 확인을 하기가 어렵습니다. 
선택된 농부를 확인할 수 있도록 변경해주세요.
농부가 선택되었다는 표시를 하면 좋을 것 같습니다.

**Comment by ksh9409255** [comment]
선택 표시 디자인을 받으면 그에 맞게 수정하겠습니다.

**Comment by ksh9409255** [comment]
수정했습니다.
